# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-12 06:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidfeed', '0005_auto_20171112_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 11, 12, 11, 54, 45, 200000)),
        ),
    ]
