# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-13 11:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidfeed', '0006_auto_20171112_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='bought',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='customer',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='product',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 11, 13, 17, 10, 27, 918000)),
        ),
    ]
