# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-13 13:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidfeed', '0007_auto_20171113_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(default=b'product description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 11, 13, 19, 5, 30, 292000)),
        ),
    ]
