# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-13 13:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidfeed', '0008_auto_20171113_1905'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default=b'whatever', max_length=100)),
                ('last_name', models.CharField(default=b'whatever', max_length=100)),
                ('contact', models.IntegerField(default=b'whatever')),
                ('Address', models.CharField(default=b'whatever', max_length=300)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 11, 13, 19, 17, 24, 378000)),
        ),
    ]
