# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-14 20:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidfeed', '0009_auto_20171113_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 11, 15, 1, 46, 37, 765000)),
        ),
    ]
