# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-15 21:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidfeed', '0011_auto_20171116_0237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 11, 16, 2, 38, 0, 682000)),
        ),
    ]
