# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-16 17:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidfeed', '0013_auto_20171116_2306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='csvf',
        ),
        migrations.AlterField(
            model_name='product',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 11, 16, 23, 9, 59, 612000)),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(max_length=400),
        ),
    ]
